### PR TITLE
Add Nth of N counting to statusline when searching a word

### PR DESCRIPTION
**Pull request by joeky888**
Ideas from [here](https://stackoverflow.com/a/23724875) and [here](https://stackoverflow.com/a/4671105)

Notice the numbers on the statusline [Nth of N]
GIF

### CODE REVIEW

**Comment by joeky888** [comment]
I also post this on vim issues [https://github.com/vim/vim/issues/453#issuecomment-324723032](https://github.com/vim/vim/issues/453#issuecomment-324723032)

I don't really test this code.
Hopefully someone can update this :)

**Comment by joeky888** [comment]
Vim will add this feature recently as a built-in option.

See [https://github.com/vim/vim/issues/453#issuecomment-324908322](https://github.com/vim/vim/issues/453#issuecomment-324908322)

Close #29

**Comment by sd65** [comment]
You're such passionate about Vim, thanks for the information!

**Comment by joeky888** [comment]
I will never use vim if you didn't create the awesome MiniVim configuration.

Anyway, here is adding support for Alt key in terminal emulators

```
" Terminal Alt + Backspace kill a word
nnoremap <Esc><BS> dBi
inoremap <Esc><BS> <C-w>
vnoremap <Esc><BS> d
cnoremap <Esc><BS> <C-w>
" Terminal Alt + Right - Next word
nnoremap <ESC>[1;3C w
inoremap <ESC>[1;3C <C-Right>
vnoremap <ESC>[1;3C 5l
nnoremap <ESC>[C w
inoremap <ESC>[C <C-Right>
vnoremap <ESC>[C 5l
nnoremap <ESC>[1;5C w
inoremap <ESC>[1;5C <C-Right>
vnoremap <ESC>[1;5C 5l
nnoremap <ESC>[1;9C w
inoremap <ESC>[1;9C <C-Right>
vnoremap <ESC>[1;9C 5l
" Terminal Alt + Left - Previous word
nnoremap <ESC>[1;3D b
inoremap <ESC>[1;3D <C-Left>
vnoremap <ESC>[1;3D 5h
nnoremap <ESC>[D b
inoremap <ESC>[D <C-Left>
vnoremap <ESC>[D 5h
nnoremap <ESC>[1;5D b
inoremap <ESC>[1;5D <C-Left>
vnoremap <ESC>[1;5D 5h
nnoremap <ESC>[1;9D b
inoremap <ESC>[1;9D <C-Left>
vnoremap <ESC>[1;9D 5h

" GVim/MacVim (This is not necessary since the Ctrl key works very well on GUI)
if has("gui_running")
  " Alt - Backspace kill a word
  nnoremap <A-BS> dBi
  inoremap <A-BS> <C-w>
  vnoremap <A-BS> d
  cnoremap <A-BS> <C-w>
  " Alt - Arrow, Move a word
  nnoremap <A-Right> w
  inoremap <A-Right> <C-Right>
  vnoremap <A-Right> 5l
  nnoremap <A-Left> b
  inoremap <A-Left> <C-Left>
  vnoremap <A-Left> 5h
endif
```

Since different terminals send different key codes, I have to consider all possible values, that's why the code is so long.

Tested on the modern terminal emulators.

I don't have an Apple device, but I believe Alt key is the Option key on the keyboard.

**Comment by joeky888** [comment]
[https://github.com/sd65/MiniVim/issues/23#issuecomment-321960362](https://github.com/sd65/MiniVim/issues/23#issuecomment-321960362)

And... What do you think about the code of the old thread?

**Pull request closed without merging**
